### PR TITLE
Docs: Improve readme and contributing guide

### PR DESCRIPTION
**Pull request by Krinkle**
Read me:
* Use official icon+text logo, and center it.
* Remove long heading.
* Shorted the intro and match the phrasing of <https://qunitjs.com/about/>.
* State "no dependencies" right here, front and center.

Contributing:
* Add extra pointer to chat.
* Mention and explain "good first issue" and "help welcome" labels.

Docs:
* Add table of contents for easier in-repo browsing.
* Make heading a link to the live site.

### CODE REVIEW

**Comment by Krinkle** [comment]
Preview at: <https://github.com/qunitjs/qunit/tree/readme-plus#readme>

/cc @gabrielcsapo @ventuno @smcclure15 Thoughts?

**Comment by Krinkle** [comment]
Preview at: <https://github.com/qunitjs/qunit/tree/readme-plus#readme>

/cc @gabrielcsapo @ventuno @smcclure15 @raycohen Thoughts?

**Review by smcclure15 — APPROVED** [review]
Very succinct and streamlined. Reads very well! Thanks for cleaning this up, it will go a long way I think

**Review by ventuno — APPROVED** [review]
LGTM. Thanks for doing this!

**Review by ventuno — APPROVED** [review]

**Pull request merged**
