### PR TITLE
Core: Ensure late-add high-priority tests are inserted in proper order

### PR DESCRIPTION
**Pull request by trentmwillis**
As mentioned in this comment: https://github.com/qunitjs/qunit/pull/1260/files#r169779552

(Note: Test has some weird behavior in PhantomJS, but verified it works as expected in Chrome, Safari, and FireFox)

### CODE REVIEW

**Comment by Arkni** [comment]
The weird behavior in PhantomJS is due to `QUnit.config.reorder` being reset to `false` inside of `grunt-contrib-qunit`'s bridge file , see [`grunt-contrib-qunit/phantomjs/bridge.js#L20-L21`](https://github.com/gruntjs/grunt-contrib-qunit/blob/52914729918b19c447ff3c98407680eaf6a297e4/phantomjs/bridge.js#L20-L21). Those 2 lines were there since the first commit.

**Comment by trentmwillis** [comment]
Thanks for that insight, I would have never figured that out! Will update the comment in the test then.

**Comment by trentmwillis** [comment]
Comment in the test has been updated. Should be good to go now I think.

**Comment by trentmwillis** [comment]
@qunitjs/qunit-team would one of you mind reviewing this for me?

**Pull request merged**
