### PR TITLE
Build: Re-introduce code coverage

### PR DESCRIPTION
**Pull request by trentmwillis**
Fixing the last part of #1048.

This takes a more explicit approach to coverage. It does the following:
1. Builds the library
2. Instruments the code
3. Copies the instrumented code to the build output so that it is used within the tests
4. Runs the tests
5. Restores the original build output
6. Stores the coverage and generates reports
7. Sends coverage to coveralls

### CODE REVIEW

**Comment by trentmwillis** [comment]
@leobalter I think we may need to update the coveralls repo so that we can send the metrics (I bet it's still pointing to `jquery/qunit`).

**Comment by leobalter** [comment]
closed with: 

- a46fbb53b8c25a8535cf991118c5d6a1838063aa
- 7dfe400719bb814dbd7becc5756d76fad63410b9
- 294ba438cb76edd61bfa5385002734440d1a676f
- 365f8d24524e1faaceb4c98b460d060abed172cc

Thanks for this amazing work!

**Comment by dorgan** [comment]
So does this mean qunit, now has code coverage??  I am running into the same issues you are ran into, our projects use grunt-qunit-istanbul in order to do code coverage and now phantomjs doesnt work with sierra, would be great if qunit now has this natively.

**Comment by leobalter** [comment]
we don't have any direct integration with coverage tools in our API. This PR only reapplied the coverage check for the own QUnit tests, testing QUnit.

**Comment by leobalter** [comment]
Working on an open source base, where every maintainer have to find available free time for the project, we can't afford to ship any coverage tool right now. Some other priorities (like using QUnit in the node cli) are a bit more valuable at this current point. Coverage integration can still be done.

btw, if we have the cli ready, we could just call `istanbul qunit ...` that would be amazing

**Pull request closed without merging**
