### PR TITLE
HTML Reporter: Fuzzy search using fuzzysort

### PR DESCRIPTION
**Pull request by ventuno**
Sample implementation of: https://github.com/qunitjs/qunit/issues/1438 ([`fuzzysort`](https://github.com/farzher/fuzzysort)-based).

Below search results with different keywords (on `test/index.html`). The examples below use different values of `fuzzysort`'s `threshold` option.
`-10000` is the value used in `fuzzysort`'s documentation: [How To Go Fast · Performance Tips](https://github.com/farzher/fuzzysort#how-to-go-fast--performance-tips) section.

#### Searches with `threshold` `undefined` (default)
Search: "assert".
fuzzysort assert

Search: "beforeEach".
fuzzysort beforeEach

Search: "promiseaware".
fuzzysort promiseaware

Search: "script".
fuzzysort script

#### Searches with `threshold` `-10000`
Search: "assert".
fuzzysort assert (threshold -10000)

Search: "beforeEach".
fuzzysort beforeEach (threshold -10000)

Search: "promiseaware".
fuzzysort promiseaware (threshold -10000)

Search: "script".
fuzzysort script (threshold -10000)

### CODE REVIEW

**Comment by trentmwillis** [comment]
We don't have regularly scheduled releases. That said, I can probably cut a new release this weekend assuming no other bugs/features come up that we'd want to wait for. Will likely be a patch release since this shouldn't affect how tests run at all.

**Comment by ventuno** [comment]
That's great. Thanks a lot for your help!

**Comment by ventuno** [comment]
@trentmwillis I see a new release was made, but I don't see this feature in the latest version. Any chance we could get this out?

**Comment by Krinkle** [comment]
@ventuno I'm running through the release process now, sorry about the delay. Ref https://github.com/qunitjs/qunit/issues/1463.

**Comment by ventuno** [comment]
Thanks for the update @Krinkle :-).

**Pull request merged**
