### PR TITLE
HTML Reporter: Fix XHTML output (issue 1255).

### PR DESCRIPTION
**Pull request by shlomif**
See https://github.com/qunitjs/qunit/issues/1255 . There was a tag without a closing / that confused the browser when using XHTML.

### CODE REVIEW

**Comment by shlomif** [comment]
@platinumazure : I'll try to, thanks for your comment.

**Comment by shlomif** [comment]
@platinumazure : added a test - it gets stuck w the fix commit reverted and succeeds with the change. see commit 545741888eb442d9f9d23b088bd41961aa2298bd .

**Comment by platinumazure** [comment]
Thanks @shlomif!

This looks good to me, but I'd like another set of eyes on this before merging.

**Comment by shlomif** [comment]
On Thu, 04 Oct 2018 05:38:48 -0700
Kevin Partington <notifications@github.com> wrote:

> Thanks @shlomif!
> 
> This looks good to me, but I'd like another set of eyes on this before
> merging.
> 

thanks!

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://www.shlomifish.org/humour/ways_to_do_it.html

XSLT is the number one cause of programmers’ suicides since Visual Basic 1.0.
    — http://www.shlomifish.org/humour/bits/facts/XSLT/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
On Mon, 08 Oct 2018 13:07:31 -0700
Trent Willis <notifications@github.com> wrote:

> Merged #1317 into master.
> 

thanks, and you are welcome!

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Funny Anti-Terrorism Story - http://shlom.in/enemy

SMG: It was 1997-1998ish, Buffy started airing. So one day a group of
yeshivah pupils arrived to the studios saying they have some numereological
insights from the Jewish bible, about what will happen in Sunnydale next.
    — http://www.shlomifish.org/humour/Summerschool-at-the-NSA/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Pull request merged**
