### PR TITLE
Build: Add yarn.lock

### PR DESCRIPTION
**Pull request by leobalter**
In case we want to use [yarn](https://yarnpkg.com/), we can start with this lock file.

### CODE REVIEW

**Comment by leobalter** [comment]
The lock is up to date, even though, I'll check how to use it on Travis CI as well

**Comment by leobalter** [comment]
because of this commit (isolated in this branch), travis is reporting a broken build on the master branch...

**Comment by trentmwillis** [comment]
@leobalter, I saw that to. I restarted the job and it seems fine now.

**Comment by trentmwillis** [comment]
Can we add `yarn` to the Travis cache? If we do that and get CI green (unsure why it's failing), I am :+1: to merge. I love using Yarn.

**Comment by trentmwillis** [comment]
@leobalter hope you don't mind, opened #1095 to supersede this (includes better caching between builds and rebased on latest `master`)

**Pull request closed without merging**
