### PR TITLE
CLI: Sane Bump

### PR DESCRIPTION
**Pull request by stefanpenner**
* modernized code-base (node 6+)
* no other changes

### CODE REVIEW

**Comment by trentmwillis** [comment]
Can you regenerate yarn.lock? Assuming tests pass after that I'll merge.

**Comment by stefanpenner** [comment]
@trentmwillis oops, yup fixing

**Comment by platinumazure** [comment]
@trentmwillis Is this a semver-major change (if we're dropping support for older Node versions)? Or would this be handled by our Rollup config?

**Comment by trentmwillis** [comment]
@platinumazure I believe we stop supporting Node versions when they leave LTS without necessarily doing a major version bump. This is a "rolling" policy similar to what we do for browsers. Here's the original discussion for more context https://github.com/qunitjs/qunit/pull/1025#issuecomment-236702128.

We wanted to go this route so that we could drop legacy versions of Node without having to do a major version bump every time.

Let me know if you see any issue with that. We've already dropped Node 4 from our Travis config.

**Comment by platinumazure** [comment]
No issue here, forgot about that discussion. In some other projects I'm on, this would be a major version bump. Thanks!

**Comment by trentmwillis** [comment]
Landing this and it'll go out in the next release (which I plan to be a minor 2.7.0)

**Pull request merged**
