### PR TITLE
Core: Ensuring semaphores are balanced when timeout occurs

### LINKED ISSUE #1375: Semaphore imbalance when returned promise resolves when test timed out.
## Tell us about your runtime:

* **QUnit version**:2.9.1
* **What environment are you running QUnit in? (e.g., browser, Node)**: Browser & Node
* **How are you running QUnit? (e.g., script, testem, Grunt)**: `qunit` Node CLI / `testem`

## What are you trying to do?

A test returning a promise (or an `async`) that runs longer than the allowed timeout period, causes an internal test semaphore imbalance if the returned promise ever settles.

Code that reproduces the problem:

```js
QUnit.module('group of tests', function(hooks) {
  QUnit.test('one', function(assert) {
	assert.timeout(10);

    return new Promise(resolve => setTimeout(resolve, 20));
  });

  QUnit.test('two', function(assert) {
   	return new Promise(resolve => setTimeout(resolve, 20))
      .then(() => {
        assert.ok(true, 'all is well');
      });
  });
});
```

[CodePen Demo Here](https://codepen.io/rwjblue/pen/GzLqXa)

If you have any relevant configuration information, please include that here:

## What did you expect to happen?

Test `one` should fail (due to timeout), and test `two` should pass.

## What actually happened?

Test `one` fails properly (due to timeout), however test `two` _also_ fails with the following message:

```
Tried to restart test while already started (test's semaphore was 0 already)
```

### PR DESCRIPTION
**Pull request by scalvert**
Fixes #1375

### CODE REVIEW

**Comment by stefanpenner** [comment]
restarting the 2 failed jobs @scalvert you may need to investigate the failures if the reoccur.

**Comment by scalvert** [comment]
Fixed. The regex for the tap output needed to be loosened to account for different stacks in versions of node.

**Comment by stefanpenner** [comment]
I don't think I can release, so other maintainers will have to help with that yet.

**Comment by trentmwillis** [comment]
Thanks! I'll cut a new release tomorrow.

**Comment by scalvert** [comment]
Thanks, @trentmwillis! This one has been plaguing us for a while!

**Pull request merged**
