### PR TITLE
Build: Prepare 2.15.0 release

### PR DESCRIPTION
**Pull request by Krinkle**

### CODE REVIEW

**Comment by Krinkle** [comment]
@nlfurniss @zackthehuman

Thanks again for your first contribution to QUnit this release! I'm writing a short post for Twitter & Mastodon and wanted to check with you whether it'd be okay to mention you there in my thanks. If so, let me know if you'd prefer I mention your social handle, GitHub username, or full name. (I won't mention you unless you say yes and how within the next few days; It's okay not to answer if you're not sure!)

**Comment by nlfurniss** [comment]
@Krinkle fine to be mentioned by github username 😊

**Comment by zackthehuman** [comment]
I'm fine with `Zack Mulgrew @zackthehuman` if that works for you. Unfortunately my handle is not the same on all platforms so including both GitHub username and my real name would nice.

**Comment by Krinkle** [comment]
@zackthehuman Sorry, I just want to double-check. Should I omit the `@` in our tweet, or is [@zackthehuman](https://twitter.com/zackthehuman) yours? (On your site I found [@ztheh](https://twitter.com/ztheh) instead.)

**Comment by zackthehuman** [comment]
@Krinkle Ah, I see. Yes, [@ztheh](https://twitter.com/ztheh) is my Twitter handle, whereas @zackthehuman is my GitHub. I wish I could claim the same one of Twitter but someone else has it. Feel free to use [@ztheh](https://twitter.com/ztheh).

**Pull request merged**
