### PR TITLE
Fail test when passing a non string value to assert.step

### PR DESCRIPTION
**Pull request by Arkni**
Ref: https://github.com/qunitjs/qunit/pull/1261#issuecomment-364330296

### CODE REVIEW

**Comment by Arkni** [comment]
@platinumazure 

That would make it readable indeed, but almost all assertion methods (except for `assert.async()`) are reusing `this.pushResult`. And as a result, I didn't want to diverge from that pattern.

**Comment by platinumazure** [comment]
Thanks for that feedback. I would love to move away from that pattern if
possible- there are enough cryptic sections in the source code. So I will
happily work to change all those other places, if that is the direction the
team wants to move in.

Maybe the fairest thing to do would be to get a second opinion. It is in
that spirit of collaboration that I marked my review as a Comment rather
than Request Changes.

**Comment by Arkni** [comment]
I updated the docs of `assert.step()` to note that non-string values also fail the step.

**Comment by platinumazure** [comment]
Works for me. I don't have an objection against this PR itself. Hopefully I can find some time later to fix that anti-pattern.

**Pull request merged**
